"""Add score to form

Revision ID: 315291bf947f
Revises: 8a6064e286b3
Create Date: 2025-05-28 16:48:25.857196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315291bf947f'
down_revision = '8a6064e286b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
