"""Add user_id and company_name to Response

Revision ID: 8a6064e286b3
Revises: 8db1ed70dba6
Create Date: 2025-05-27 17:35:02.222888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6064e286b3'
down_revision = '8db1ed70dba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('company_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
